<!doctype html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Dashboard SEO | Noindex</title>
<meta name="robots" content="noindex, nofollow">
<style>
body{font-family:Arial,sans-serif;background:#f4f8f8;margin:0;color:#102e33}.wrap{max-width:1250px;margin:auto;padding:24px}.card{background:#fff;border-radius:22px;padding:22px;margin:16px 0;box-shadow:0 10px 28px rgba(0,0,0,.08)}button,.btn{background:#2BB2AF;color:#fff;border:0;border-radius:12px;padding:10px 14px;font-weight:700;text-decoration:none;cursor:pointer}.secondary{background:#3B858F!important}.danger{background:#c0392b!important}input,textarea,select{width:100%;padding:12px;margin:6px 0 12px;border:1px solid #dbe7e7;border-radius:12px}textarea{min-height:90px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.google{border:1px solid #ddd;border-radius:14px;padding:16px}.gurl{color:#188038}.gtitle{color:#1a0dab;font-size:19px}.gdesc{color:#4d5156}.score{height:10px;background:#e8f0f0;border-radius:99px;overflow:hidden}.score span{display:block;height:100%;background:linear-gradient(90deg,#2BB2AF,#3B858F)}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #eee;padding:10px;text-align:left}
</style>
</head>
<body><div id="root"></div>
<script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
<script>
const e=React.createElement,API='/api/items';
function slugify(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function pathFor(i){return i.type==='page'?'/'+(i.slug==='accueil'?'':i.slug):i.type==='offer'?'/offres/'+i.slug:i.type==='realization'?'/realisations/'+i.slug:'/blog/'+i.slug}
function score(i){let s=0,t=i.seo_title||'',d=i.seo_description||'',kw=(i.focus_keyword||'').toLowerCase(),c=(i.content||'').toLowerCase();if(t.length>=35&&t.length<=65)s+=20;if(d.length>=80&&d.length<=160)s+=20;if(kw)s+=10;if(kw&&t.toLowerCase().includes(kw.split(' ')[0]))s+=10;if(i.slug&&!i.slug.includes('_'))s+=10;if(i.robots==='index, follow')s+=10;if(i.og_image)s+=10;if(c.length>=100)s+=10;return Math.min(s,100)}
const empty={type:'blog',title:'',slug:'',content:'',seo_title:'',seo_description:'',focus_keyword:'',robots:'index, follow',status:'published',og_image:'/og.svg'};
function Preview({item}){return e('div',{className:'google'},[e('div',{className:'gurl'},location.origin+pathFor(item)),e('div',{className:'gtitle'},item.seo_title||'Titre SEO'),e('div',{className:'gdesc'},item.seo_description||'Meta description')])}
function Form({item,onSave,onCancel}){const[f,setF]=React.useState(item||empty);const u=(k,v)=>{let n={...f,[k]:v};if(k==='title'&&!f.slug)n.slug=slugify(v);setF(n)};return e('div',{className:'grid'},[e('div',{className:'card'},[e('h2',{},f.id?'Modifier':'Ajouter'),e('label',{},'Type'),e('select',{value:f.type,onChange:x=>u('type',x.target.value)},[e('option',{value:'page'},'Page'),e('option',{value:'blog'},'Blog'),e('option',{value:'offer'},'Offre'),e('option',{value:'realization'},'Réalisation')]),e('label',{},'Titre'),e('input',{value:f.title,onChange:x=>u('title',x.target.value)}),e('label',{},'Slug'),e('input',{value:f.slug,onChange:x=>u('slug',slugify(x.target.value))}),e('label',{},'Contenu'),e('textarea',{value:f.content,onChange:x=>u('content',x.target.value)}),e('label',{},'Robots'),e('select',{value:f.robots,onChange:x=>u('robots',x.target.value)},[e('option',{},'index, follow'),e('option',{},'noindex, nofollow')])]),e('div',{className:'card'},[e('h2',{},'SEO'),e('label',{},'SEO Title'),e('input',{value:f.seo_title,onChange:x=>u('seo_title',x.target.value)}),e('label',{},'Meta Description'),e('textarea',{value:f.seo_description,onChange:x=>u('seo_description',x.target.value)}),e('label',{},'Focus Keyword'),e('input',{value:f.focus_keyword,onChange:x=>u('focus_keyword',x.target.value)}),e('label',{},'OG Image'),e('input',{value:f.og_image,onChange:x=>u('og_image',x.target.value)}),e('h3',{},'Score '+score(f)+'/100'),e('div',{className:'score'},e('span',{style:{width:score(f)+'%'}})),e(Preview,{item:f}),e('p',{},[e('button',{onClick:()=>onSave(f)},'Enregistrer'),' ',e('button',{className:'secondary',onClick:onCancel},'Annuler')])])])}
function App(){const[items,setItems]=React.useState([]),[edit,setEdit]=React.useState(null),[filter,setFilter]=React.useState('all');const load=()=>fetch(API).then(r=>r.json()).then(setItems);React.useEffect(load,[]);const save=async(i)=>{await fetch(i.id?API+'/'+i.id:API,{method:i.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(i)});setEdit(null);load()};const del=async(id)=>{if(confirm('Supprimer ?')){await fetch(API+'/'+id,{method:'DELETE'});load()}};if(edit)return e('div',{className:'wrap'},[e(Form,{item:edit,onSave:save,onCancel:()=>setEdit(null)})]);let shown=filter==='all'?items:items.filter(i=>i.type===filter);return e('div',{className:'wrap'},[e('div',{className:'card'},[e('a',{className:'btn secondary',href:'/'},'Site public'),' ',['all','blog','offer','realization','page'].map(f=>e('button',{className:'secondary',onClick:()=>setFilter(f)},f)),' ',e('a',{className:'btn secondary',href:'/sitemap.xml',target:'_blank'},'Sitemap')]),e('div',{className:'card'},[e('h1',{},'Dashboard SEO Laravel 8'),e('button',{onClick:()=>setEdit(empty)},'+ Ajouter')]),e('div',{className:'card'},e('table',{},[e('thead',{},e('tr',{},['Type','Titre','Score','URL','Preview','Actions'].map(h=>e('th',{},h)))),e('tbody',{},shown.map(i=>e('tr',{},[e('td',{},i.type),e('td',{},i.title),e('td',{},score(i)+'/100'),e('td',{},e('a',{href:i.path,target:'_blank'},i.path)),e('td',{},e(Preview,{item:i})),e('td',{},[e('button',{className:'secondary',onClick:()=>setEdit(i)},'Modifier'),' ',e('button',{className:'danger',onClick:()=>del(i.id)},'Supprimer')])])))]))])}
ReactDOM.createRoot(document.getElementById('root')).render(e(App));
</script></body></html>
